const BAD_REQUEST_ERR = 400;
const AUTH_ERR = 401;
const FORBIDDEN_ERR = 403;
const NOT_FOUND_ERR = 404;
const REPEAT_ERR = 409;
const INTERNAL_SERVER_ERR = 500;

module.exports = {
  BAD_REQUEST_ERR,
  AUTH_ERR,
  FORBIDDEN_ERR,
  NOT_FOUND_ERR,
  REPEAT_ERR,
  INTERNAL_SERVER_ERR,
};
